export const requestsActionTypes = {
  GET_REQUESTS: "GET_REQUESTS",
  GET_REQUESTS_SUCCESS: "GET_REQUESTS_SUCCESS",
  GET_REQUESTS_FAIL: "GET_REQUESTS_FAIL",
  DELETE_REQUESTS: "DELETE_REQUESTS",
  DELETE_REQUESTS_SUCCESS: "DELETE_REQUESTS_SUCCESS",
  DELETE_REQUESTS_FAIL: "DELETE_REQUESTS_FAIL",
  PRINT_LIST: "PRINT_LIST",
  PRINT_LIST_SUCCESS: "PRINT_LIST_SUCCESS",
  PRINT_LIST_FAIL: "PRINT_LIST_FAIL",
}
